#!/bin/bash
# On hr-bastion: write ~/.ssh/config Host aliases for every InService app guest.
# Installed as /usr/local/bin/hr-ssh-config. IPs change on ASG replace; re-run
# this (or open a new SSM session — .bashrc calls it) before ssh.
# Never prints PEMs.
set -euo pipefail

export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"

ROLES=(portal rest haystack neo4j)

if [ "$(id -u)" -eq 0 ]; then
  SSH_DIR="/home/ec2-user/.ssh"
  OWNER="ec2-user"
else
  SSH_DIR="${HOME}/.ssh"
  OWNER="$(id -un)"
fi

install -d -m 700 -o "${OWNER}" -g "${OWNER}" "${SSH_DIR}"

list_role() {
  local role="$1"
  aws ec2 describe-instances \
    --filters \
      "Name=instance-state-name,Values=running" \
      "Name=tag:Role,Values=${role}" \
    --query 'Reservations[].Instances[].[Placement.AvailabilityZone,PrivateIpAddress,InstanceId]' \
    --output text 2>/dev/null | awk 'NF>=2 {print}' | sort
}

write_config() {
  local tmp n role az ip iid az_short
  tmp="$(mktemp)"
  {
    echo "# Generated by hr-ssh-config. Do not edit; IPs change on ASG replace."
    echo "Host *"
    echo "  User ec2-user"
    echo "  IdentityFile ${SSH_DIR}/id_ed25519"
    echo "  IdentitiesOnly yes"
    echo "  StrictHostKeyChecking accept-new"
    echo
    echo "Host 10.0.*"
    echo "  User ec2-user"
    echo
    for role in "${ROLES[@]}"; do
      n=0
      while read -r az ip iid; do
        [ -n "${ip}" ] || continue
        n=$((n + 1))
        az_short="${az##*-}"
        echo "Host ${role}-${n} ${role}-${az_short}"
        echo "  HostName ${ip}"
        echo "  # ${iid} ${az}"
        echo
        if [ "${n}" -eq 1 ]; then
          echo "Host ${role}"
          echo "  HostName ${ip}"
          echo
        fi
      done < <(list_role "${role}")
    done
  } >"${tmp}"
  install -m 600 -o "${OWNER}" -g "${OWNER}" "${tmp}" "${SSH_DIR}/config"
  rm -f "${tmp}"
}

print_list() {
  local role n az ip iid
  echo "SSH from this bastion (key ${SSH_DIR}/id_ed25519):"
  echo
  printf '%-14s %-15s %-12s %s\n' "HOST" "PRIVATE_IP" "AZ" "INSTANCE"
  for role in "${ROLES[@]}"; do
    n=0
    while read -r az ip iid; do
      [ -n "${ip}" ] || continue
      n=$((n + 1))
      printf '%-14s %-15s %-12s %s\n' "${role}-${n}" "${ip}" "${az}" "${iid}"
      if [ "${n}" -eq 1 ]; then
        printf '%-14s %-15s %-12s %s\n' "${role}" "${ip}" "${az}" "(same as ${role}-1)"
      fi
    done < <(list_role "${role}")
    if [ "${n}" -eq 0 ]; then
      printf '%-14s %s\n' "${role}-*" "(no running instances)"
    fi
  done
  echo
  echo "Examples:  ssh portal    ssh rest-2    ssh haystack-1a    ssh neo4j"
}

write_config

if [ "${1:-}" = "--list" ] || [ "${1:-}" = "-l" ]; then
  print_list
fi
